# Generated by Django 2.2.3 on 2019-07-30 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetup', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='photo',
            field=models.ImageField(null=True, upload_to='group_photos'),
        ),
        migrations.AddField(
            model_name='meetup',
            name='photo',
            field=models.ImageField(null=True, upload_to='group_photos'),
        ),
    ]
