# Generated by Django 2.2.3 on 2019-07-30 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetup', '0002_auto_20190730_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='group_photos'),
        ),
        migrations.AlterField(
            model_name='meetup',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='group_photos'),
        ),
    ]
