# Generated by Django 2.2.3 on 2019-08-15 15:07

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models

from events.enums import CategoryEnum


def create_category(apps, schema_editor):
    EventCatgory = apps.get_model("events", "EventCategory")
    for key, val in CategoryEnum.choices():
        EventCatgory.objects.create(name=val)


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=240)),
                ("about", models.TextField()),
                ("image", models.ImageField(blank=True, null=True, upload_to="events/images")),
                ("location", models.CharField(max_length=240)),
                ("event_date", models.DateField()),
                ("event_time_start", models.CharField(max_length=5)),
                ("event_time_end", models.CharField(max_length=5)),
                ("chief_guest", models.CharField(max_length=200)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "rating",
                    models.PositiveIntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EventCategory",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                ("image", models.ImageField(blank=True, upload_to="category/images")),
            ],
        ),
        migrations.CreateModel(
            name="EventReview",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "rating",
                    models.PositiveIntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                ("review", models.TextField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="event_review", to="events.Event"
                    ),
                ),
            ],
        ),
        migrations.RunPython(create_category, migrations.RunPython.noop),
    ]
