# Generated by Django 2.2.3 on 2019-08-10 17:20

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
from events.enums import CategoryEnum

def create_category(apps, schema_editor):
    EventCatgory = apps.get_model('events', 'EventCategory')
    for key, val in CategoryEnum.choices():
        EventCatgory.objects.create(name=val)


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=240)),
                ('about', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='events/images')),
                ('location', models.CharField(max_length=240)),
                ('event_date', models.DateField()),
                ('ticket_amount_first', models.DecimalField(decimal_places=2, max_digits=1000)),
                ('ticket_amount_second', models.DecimalField(decimal_places=2, max_digits=1000)),
                ('event_time_start', models.CharField(max_length=5)),
                ('event_time_end', models.CharField(max_length=5)),
                ('chief_guest', models.CharField(max_length=200)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('company_name', models.CharField(max_length=240)),
                ('company_phone1', models.CharField(max_length=20)),
                ('company_phone2', models.CharField(blank=True, max_length=20, null=True)),
                ('company_email', models.EmailField(max_length=254)),
                ('company_address', models.CharField(max_length=240)),
                ('company_office', models.CharField(max_length=240)),
                ('company_web_address', models.URLField(blank=True, null=True)),
                ('rating', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('approved', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='EventCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, upload_to='category/images')),
            ],
        ),
        migrations.CreateModel(
            name='EventMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='EventReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('review', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_review', to='events.Event')),
            ],
        ),
        migrations.RunPython(create_category, migrations.RunPython.noop),
    ]
