# Generated by Django 2.2.3 on 2019-08-10 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20190810_1720'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='company_address',
        ),
        migrations.RemoveField(
            model_name='event',
            name='company_email',
        ),
        migrations.RemoveField(
            model_name='event',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='event',
            name='company_office',
        ),
        migrations.RemoveField(
            model_name='event',
            name='company_phone1',
        ),
        migrations.RemoveField(
            model_name='event',
            name='company_phone2',
        ),
        migrations.RemoveField(
            model_name='event',
            name='company_web_address',
        ),
    ]
