# Generated by Django 2.2.3 on 2019-08-15 15:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("groups", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="appgroup",
            name="member",
            field=models.ManyToManyField(related_name="group_members", to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="appgroup",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="owner", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
